- name: Configure EC2 instance and deploy app
  hosts: app
  become: true

  roles:
    - common
    - docker
    - app
-name: Configure NGINX Load Balancer
  hosts: loadbalancers
  become: yes
  roles:
    - nginx